import type { PortalMyProjectRow } from "@/lib/portal-my-projects";
import type { PortalProjectDetail } from "@/lib/portal-project";

/** `NEXT_PUBLIC_PROJECT_LIST_DEMO=1` 時のみ UI 確認用 */
export const DUMMY_PROJECT_LIST_ROWS: PortalMyProjectRow[] = [
  {
    id: 1,
    name: "デモ案件 Alpha",
    slug: "demo-alpha",
    role: "owner",
    client_name: "株式会社サンプル",
    site_type: "corporate",
    site_type_other: null,
    is_renewal: false,
    kickoff_date: "2026-03-01",
    release_due_date: "2026-06-30",
  },
  {
    id: 2,
    name: "EC リニューアル",
    slug: "demo-ec",
    role: "editor",
    client_name: "テスト商事",
    site_type: "ec",
    site_type_other: null,
    is_renewal: true,
    kickoff_date: "2026-04-15",
    release_due_date: "2026-05-20",
  },
  {
    id: 3,
    name: "会員ポータル構築",
    slug: null,
    role: "viewer",
    client_name: "デモクライアント",
    site_type: "member_portal",
    site_type_other: null,
    is_renewal: false,
    kickoff_date: "2026-02-10",
    release_due_date: null,
  },
  {
    id: 4,
    name: "オウンドメディア",
    slug: "owned-1",
    role: "owner",
    client_name: "メディア株式会社",
    site_type: "owned_media",
    site_type_other: null,
    is_renewal: false,
    kickoff_date: null,
    release_due_date: "2026-12-01",
  },
  {
    id: 5,
    name: "その他カスタム",
    slug: "other-1",
    role: "owner",
    client_name: null,
    site_type: "other",
    site_type_other: "特化サイト",
    is_renewal: true,
    kickoff_date: "2026-01-05",
    release_due_date: "2026-03-01",
  },
  {
    id: 6,
    name: "製品ポータル",
    slug: "prod",
    role: "editor",
    client_name: "製造デモ",
    site_type: "product_portal",
    site_type_other: null,
    is_renewal: false,
    kickoff_date: "2026-05-01",
    release_due_date: "2026-08-15",
  },
  {
    id: 7,
    name: "社内ポータル",
    slug: "internal",
    role: "viewer",
    client_name: "社内利用",
    site_type: "internal_portal",
    site_type_other: null,
    is_renewal: false,
    kickoff_date: "2026-06-01",
    release_due_date: "2026-09-01",
  },
  {
    id: 8,
    name: "長い名前のプロジェクトを表示したときの折り返し確認用ダミー案件名",
    slug: "long",
    role: "owner",
    client_name: "長いクライアント名株式会社オフィス",
    site_type: "corporate",
    site_type_other: null,
    is_renewal: false,
    kickoff_date: "2026-04-01",
    release_due_date: "2026-04-18",
  },
  {
    id: 9,
    name: "BtoB ポータル刷新",
    slug: "btob-portal",
    role: "owner",
    client_name: "グローバル商事",
    site_type: "corporate",
    site_type_other: null,
    is_renewal: true,
    kickoff_date: "2026-07-01",
    release_due_date: "2026-11-30",
  },
  {
    id: 10,
    name: "サブスク EC 立ち上げ",
    slug: "sub-ec",
    role: "editor",
    client_name: "サブスクデモ株式会社",
    site_type: "ec",
    site_type_other: null,
    is_renewal: false,
    kickoff_date: "2026-05-20",
    release_due_date: "2026-10-01",
  },
  {
    id: 11,
    name: "医療会員サイト",
    slug: null,
    role: "viewer",
    client_name: "メディカルデモ",
    site_type: "member_portal",
    site_type_other: null,
    is_renewal: false,
    kickoff_date: "2026-03-15",
    release_due_date: null,
  },
  {
    id: 12,
    name: "工場向けイントラ",
    slug: "factory-intra",
    role: "owner",
    client_name: "製造デモ第二",
    site_type: "internal_portal",
    site_type_other: null,
    is_renewal: false,
    kickoff_date: "2026-08-01",
    release_due_date: "2027-01-15",
  },
  {
    id: 13,
    name: "カタログ連携ポータル",
    slug: "catalog",
    role: "editor",
    client_name: "機械メーカー試作",
    site_type: "product_portal",
    site_type_other: null,
    is_renewal: true,
    kickoff_date: "2026-02-01",
    release_due_date: "2026-06-30",
  },
  {
    id: 14,
    name: "メディアハブ（その他）",
    slug: "media-hub",
    role: "owner",
    client_name: null,
    site_type: "other",
    site_type_other: "業界特化メディア",
    is_renewal: false,
    kickoff_date: "2026-09-10",
    release_due_date: "2026-12-20",
  },
  {
    id: 15,
    name: "スクロール確認用 最終行ダミー",
    slug: "scroll-check",
    role: "viewer",
    client_name: "エッジケース商事",
    site_type: "owned_media",
    site_type_other: null,
    is_renewal: false,
    kickoff_date: "2026-04-22",
    release_due_date: "2026-04-22",
  },
];

/** デモ詳細画面用: 一覧行から `PortalProjectDetail` 風のスナップショットを生成する */
export function getDummyPortalProjectDetail(projectId: number): PortalProjectDetail | null {
  const row = DUMMY_PROJECT_LIST_ROWS.find((r) => r.id === projectId);
  if (!row) {
    return null;
  }
  return {
    id: row.id,
    name: row.name,
    slug: row.slug,
    client_name: row.client_name,
    site_type: row.site_type,
    site_type_other: row.site_type_other,
    is_renewal: row.is_renewal,
    kickoff_date: row.kickoff_date,
    release_due_date: row.release_due_date,
    renewal_urls: row.is_renewal ? ["https://example.com/legacy-site"] : [],
    redmine_links: [{ redmine_project_id: 100 + row.id, redmine_base_url: null }],
    misc_links: [
      { label: "社内メモ", url: "https://example.com/memo" },
      { label: "ドライブ", url: "https://example.com/drive" },
    ],
    participants: [
      { user_id: 9201, role: "owner", display_name: "owner.demo@example.com" },
      { user_id: 9202, role: "editor", display_name: "editor.demo@example.com" },
      { user_id: 9203, role: "viewer", display_name: "viewer.demo@example.com" },
    ],
  };
}
